### ISSUE TITLE
To-do list for version 2.0

### ISSUE THREAD

**Issue by vektorious** [oberlab/portfolio#1]
- [x] Lehrplanreferenzen ergänzen (auch bei den Kurspaketen, aber **nicht** den Events)
- [x] Lehrplanreferenzen alle nocheinmal durchgehen

Ein paar Eventbeschreibungen müssen noch angepasst werden, weil es die identischen Texte sind wie von den Kursen.
- [x] TShirts
- [x] Loeten (mehr auf **Anstecker** eingehen)
- [x] Bristle
- [x] Puzzle
- [x] Brotzeitbrettl

-> Bitte mehr den Ablauf als Dauerworkshop beschreiben. Teilweise sind die Texte auch zu lang! Lieber noch etwas kürzen

- [x] Kurse müssen noch nach Kategorie sortiert werden
- [x] Die Lernziele (Learning Goals) auf Formulierung überprüfen. "Die Schüler:innen lernen xyz Kompetgenzen"
- [x] Kannst du dir für die Learning Goals für "Design und Prototyping" noch was überlegen ? <3
- [ ] Bilder machen und aufbereiten

**Comment by JaysonD** [comment]
Grüß dich ;)

**Comment by JaysonD** [comment]
https://draradech.github.io/jigsaw/jigsaw.html

(Für das Puzzle. Nur merken)

**Comment by JaysonD** [comment]
Kursstruktur:
1-13 = engineering
14-20 = code
21-33 = science

**Comment by JaysonD** [comment]
Noch sehr viele Kurse mit wir und du.  Auf was einigen wir uns jetzt?

**Comment by JaysonD** [comment]
@vektorious bitte denke an den Kurs "Luft, Wind und Wetter" <2
