### ISSUE TITLE
#TODO 

### ISSUE THREAD

**Issue by vektorious** [oberlab/portfolio#2]
- [x] Fehlende Bilder anfertigen (@JaysonD)
- [x] Reihenfolge muss optimiert werden: von einfach zu anspruchsvoll. Zusammenhängende Kurse hintereinander (z.B. die Nähkurse) (@JaysonD)
- [x] Die Texte von den Events sind zu lang. Beim "Ablauf" weniger schreiben. Keine Details sondern wie das dann auf dem Event von statten geht wie z.B. Ihr könnt jederzeit kommen und könnt nacheinander eine Müpnze Vergolden etc. (@JaysonD)
- [x] Lehrplanreferenzen von den Kurspaketen überarbeiten (@JaysonD)
- [x] Bei den Bildern bitte das naming beibehalten KURS_process.png oder KURS_result.png (@JaysonD )
- [x] Sicher stellen, dass die Bilder 600x800 (process) bzw. 800x800 (result) groß sind @JaysonD 
- [x] Alles original Bilder auf die Nextcloud legen @JaysonD 
- [x] Alle UNSKALIERTEN freigestellten Bilder auf die Nextcloud legen @JaysonD 
- [x] Alle skalierten, freigestellten Bilder kommen ins Portfolio Repo @JaysonD 
- [x] Bild result in Anfänger Nähkurs ist falsch. Da sind Beanies und keine Reisverlschluss tasche. Bitte austauschen. Wenn keine Reisverschlusstasche zur Hand nimm ne Nähmaschine.
- [x] Welt der Farben: Ich finde keines der beiden Bilder zeigt wirklich was passiert. Hast du vielleicht noch was mit Stfiten oder so?
- [x] ISt das Bild links von der Wetterstation verzerrt? Wir hatten auf jeden Fall gesagt dass da ein anderes Bild rein muss. Zwei mal eine offene Station bringt ja nix.
- [x] Bei mehr Calliope Projekte ist das gleiche Bild wie bei Calliope Projekte
- [x] Text bei Brotzeitbrettl Lasern bei Events ist noch zu lang.
- [x] Anstatt dem Bild von der Präsentation beim Experimentierklub bitte irgendwas bei dem Experimentiert wird. Vielleicht das Bild mit den Camera Obscura?

---
- [x] Bilder für die Kapitel raussuchen und einbauen (@vektorious)
- [x] Fertig machen: 03_Mikrobenuniversum/26_LuftWindWetter (@vektorious)
- [x] "duration_school" bei dem Schulportfolio hinzufügen (@vektorious)
- [x] Mehr Infos zum Ablauf an der Schule hinzufügen (@vektorious)
- [x] Mikroskop Bilder austauschen
- [x] Bild Mikrobenuniversum
- [x] Bild Prototyping
- [x] CodingKids

**Comment by JaysonD** [comment]
- [x] Größen im normalen Portfolio anpassen (@JaysonD)

**Comment by JaysonD** [comment]
- [x] Bilder zu Luft und Wind in beiden Portfolios wieder einfügen (@vektorious)
- [x] Coding kids result und process sind noch identisch (@vektorious)
